title: MATD Experiment
desc:
baseurl:  /matd-project
font_name: experiment
family_name: Experiment
family_weight_1: Regular
family_weight_2: ExtraBold
thumb_url:
string_sinhala: රටවට රටවට වපර රටවට පර රටවට ව චර රසට වරට සසර රස වසට රටවට රටට සසර රටවට රටවට සවස සසර වසර ප රසට රටවට සර රටවට රටවට චර රටවට රට සර රටවට චර වපර සසර රව රටවට රටවට රටවට චර රසට වසර රටවට රටවට රටවට රටවට රටවට වපර පස වර සවස රටවට වසට රටවට රසට රටවට පවස සස රටවට රස රටවට රටවට පවස රටවට රටවට රටවට රසට වට වසට රටවට රටවට චර රටවට රටවට රටට වර පසට රටවට සසර රට චර සට වපර පවස ට පවට ස වරට රටවට රටවට පස රසට රව රටවට පර සවස රට රටවට රටවට රටවට වරට සසර රටවට සවස පසට රටවට රටවට පවස රටවට ට සවස සස වස රටවට වසට රටට රටවට සට රට රටට රටවට සස රටවට රටවට වපර රටවට රටවට රටවට වපර රටට රටවට ස වසර වස රටවට
string_tamil:
string_latin: anna anana dan add anana ananda nan and an dan an nada anna a dada ananda dan danda add an anana and dada nada add anna dad and anana dada anna ananda nada anna an dad ananda dada nada a anana an ananda dada an ananda anana an and anana anana danda danda anana add ananda anna nada an an an and danda ananda dada nada ananda nan a an dad a ananda dan an dad danda nada an anana ananda dan an add an ananda anna dada anana dad dada anana dada dada nada anna ananda an dada anana dad ananda nada dada nada danda dada dada nan anna an dad danda ananda an ananda an add nada anana anna anana anana danda and an add anana dada and add danda a dada anana anna danda ananda nada an ananda nada an danda dada dada and ananda dada nada anana nada danda nada and anana an ananda an nada an dad anna anna dad anana add dad nada danda ananda add an danda add an dan anna danda ananda a dan ananda dad nan dada an and add danda anana an anna dad an ananda anana anna
glyphs: අ ආ ඇ ඈ ඉ ඊ උ ඌ ඍ ඎ ඏ ඐ එ ඒ ඓ ඔ ඕ ඖ ක ඛ ග ඝ ඞ ඟ ච ඡ ජ ඣ ඤ ඥ ඦ ට ඨ ඩ ඪ ණ ඬ ත ථ ද ධ න ඳ ප ඵ බ භ ම ඹ ය ර ල ව ශ ෂ ස හ ළ ෆ ෴ ෛ ෙ ා ෘ ු ූ ැ ෑ ෟ ි ී 0 1 2 3 4 5 6 7 8 9 ( { [ . , ¡ ! ¿ ? * ' ‘ ’ " “ ” ] } ) $ € £ % @ & ¶ § ¢ † ‡ abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
string_mix: රටවට රටවට වපර රටවට පර රටවට ව චර රසට වරට සසර රස වසට රටවට රටටanna anana nan anna anana a nan an nan nan nan anana nan an anana anna anna  සසර රටවට රටවට සවස සසර වසර ප රසට රටවට සර රටවට රටවට චර රටවට රට සර රටවට චර වපර සසර රව රටවට රටවට රටවට චර රසට වසර රටවට රටවට රටවට රටවට රටවට වපර පස වර සවස රටවට වසට රටවට රසට රටවට පවස සස රටවට රස රටවට රටවට පවස රටවට රටවට රටවට රසට වට වසට රටවට රටවට චර රටවට රටවට රටට වර පසට රටවට සසර රට චර සට වපර පවස ටanna anana nan anna anana a nan an nan nan nan anana nan an anana anna anna  පවට ස වරට රටවට රටවට පස රසට රව රටවට පර සවස රට රටවට රටවට රටවට වරට සසර රටවට සවස පසට රටවට රටවට පවස රටවට ට සවස සස වස රටවට වසට රටට රටවටanna anana nan anna anana a nan an nan nan nan anana nan an anana anna anna  සට රට රටට රටවට සස රටවට රටවට වපර රටවට රටවට රටවට වපර රටට රටවට ස වසර වස රටවට
safe: false
lsi: false


# About/contact
author:
  name:              Pathum Egodawatta
  url:               https://twitter.com/pathumego
  email:             pathum@mooniak.com

# Custom vars
version:             0.0.1

exclude:
  - README.md
  - TRADEMARKS.md
  - FONTLOG.md
  - COPYRIGHT.md
  - scripts
  - sources
  - documentation
